### ISSUE TITLE
bedfiles does not contain the genes I am searching 

### ISSUE THREAD

**Issue by qicaibiology** [stephenfloor/extract-transcript-regions#5]
I have used the script to extract 5utr/3utr/cds from a gtf file. I have used the same gtf file to do genome indexing and STAR mapping. Then I tried to do bedtools intersect to extract the location of my filtered introns.
I cannot get any overlapping from any of these features. So I opened some bedfile and type a gene but unexpectedly, I can not find the gene's name in the bed6 files.

What could be the potential problem?

my code for extracting features is:
`python extract_transcript_regions.py -i  GRCm38_gene_125bp.gtf -o GRCm38_genes --gtf`
`cat GRCm38_genes_3utr.bed | bed12ToBed6 -i stdin -n > GRCm38_genes_3utr_bed6.bed`
`bedtools intersect -nonamecheck -u -s -a All_retained_intron.bed -b GRCm38_genes_cds_bed6.bed > IR_in_CDS.bed `

I have tried several regions. None throw out overlapping.

What could be the underlying problems?

**Comment by stephenfloor** [comment]
Hi, glad the script worked! The gene name/ID etc in the resulting bed files will depend on the GTF being used, and may contain IDs but not gene names. Since it is running properly to extract regions, issues experienced downstream fall into the category of overall bioinformatics. My guess is a chromosome name or other mismatch between bed formats. I encourage you to post to a general bioinformatics forum or ask locally for help as I am unable to support issues beyond the scope of "extract transcript regions" itself.
